Configor:
  DataStream:
    # key: event camera topic, value: event type. Supported event types:
    # 1. PROPHESEE_EVENT: https://github.com/prophesee-ai/prophesee_ros_wrapper.git
    # 2. DVS_EVENT: https://github.com/uzh-rpg/rpg_dvs_ros.git
    EventTopics:
      - key: "/dvs/events"
        value:
          Type: "DVS_EVENT"
          Width: 346
          Height: 260
    BagPath: "/home/csl/dataset/event_develop/data_2024_12_01.bag"
    # the time piece: [BegTime, BegTime + Duration], unit: second(s)
    # if you want to use all time data for calibration, please set them to negative numbers
    # Note that the 'BegTime' here is measured from the start time of bag
    # and is not related to the timestamp of the data recorded in the package.
    BeginTime: -1
    Duration: -1
    OutputPath: "/home/csl/ros_ws/eKalibr/src/ekalibr/data/test"
  Prior:
    # decay of the surface of active events, unit: sec
    DecayTimeOfActiveEvents: 0.02
    # extraction of circular shapes based on raw events
    CircleExtractor:
      # clusters with an area greater than the following threshold value are considered valid clusters, unit: pixels.
      ValidClusterAreaThd: 10
      # two matched circular clusters whose average directional difference of norm flows,
      # should be less than the following threshold value, unit: degrees.
      CircleClusterPairDirThd: 30
      # When fitting a time-varying circular in the spatiotemporal domain,
      # the distance from the event to the circle should be less than the following threshold value, unit: pixels.
      PointToCircleDistThd: 2.0
  Preference:
    # supported data output format:
    # 1. JSON
    # 2. XML
    # 3. YAML
    # 4. BINARY (not recommended)
    OutputDataFormat: "YAML"
    Visualization: false
